name: models
description: "General purpose models for usage in UI, Data and Domain layer."
version: 0.0.1
homepage: https://github.com/maranix/ubiq/tree/main/app/packages/models
publish: none

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dart_mappable: ^4.2.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  dart_mappable_builder: ^4.2.3

flutter:
